/*
 * SWIFT Banking Analytics
 *
 * SWIFT Watch Banking Analytics API enables institutions to retrieve their  own SWIFT traffic data and the SWIFT totals, extending to the level of value and currency per market.   **v1.0.11 Release Notes**   * The Test Environment url updated to https://api-pilot.swift.com/bi/banking-analytics/v1  * PaginationLinks Object is defined as optional, as well as property next.   * Response examples were udpated to align with the API contract.   * Example for Market parameter in the request fixed
 *
 * API version: 1.0.11
 * Contact: developer-support@swift.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package analytics
// ProprietaryCurrency1Code : > Specifies a currency in a proprietary, coded form. *`NCFD_no_currency_and_value_found`-No currency and value found during recon. *`NTAV_not_available`-Information is not available. *`OTHR_other`-Other than an ISO 4217 currency code.
type ProprietaryCurrency1Code string

// List of ProprietaryCurrency1Code
const (
	NCFD_NO_CURRENCY_AND_VALUE_FOUND_ProprietaryCurrency1Code ProprietaryCurrency1Code = "NCFD_no_currency_and_value_found"
	NTAV_NOT_AVAILABLE_ProprietaryCurrency1Code ProprietaryCurrency1Code = "NTAV_not_available"
	OTHR_OTHER_ProprietaryCurrency1Code ProprietaryCurrency1Code = "OTHR_other"
)
