/*
 * SWIFT Banking Analytics
 *
 * SWIFT Watch Banking Analytics API enables institutions to retrieve their  own SWIFT traffic data and the SWIFT totals, extending to the level of value and currency per market.   **v1.0.11 Release Notes**   * The Test Environment url updated to https://api-pilot.swift.com/bi/banking-analytics/v1  * PaginationLinks Object is defined as optional, as well as property next.   * Response examples were udpated to align with the API contract.   * Example for Market parameter in the request fixed
 *
 * API version: 1.0.11
 * Contact: developer-support@swift.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package analytics
// ProprietaryGeoRegionInformation1Code : > Contains information about a country or geographical region in a proprietary, coded form. *`BILA_bilaterally_agreed`-Bilaterally agreed. *`EPTY_empty_element`-Empty element. *`FREE_free_format`-Free format. *`GIMI_global_imi`-Global IMI *`INTI_international_instrument`-International Instrument. *`NOTA_not_available`-Not available. *`OTHR_other`-Other. *`SWFT_swift`-SWIFT *`TGT2_target2`-Target 2 *`TCKS_ticker_symbol`-Ticker Symbol
type ProprietaryGeoRegionInformation1Code string

// List of ProprietaryGeoRegionInformation1Code
const (
	BILA_BILATERALLY_AGREED_ProprietaryGeoRegionInformation1Code ProprietaryGeoRegionInformation1Code = "BILA_bilaterally_agreed"
	EPTY_EMPTY_ELEMENT_ProprietaryGeoRegionInformation1Code ProprietaryGeoRegionInformation1Code = "EPTY_empty_element"
	FREE_FREE_FORMAT_ProprietaryGeoRegionInformation1Code ProprietaryGeoRegionInformation1Code = "FREE_free_format"
	GIMI_GLOBAL_IMI_ProprietaryGeoRegionInformation1Code ProprietaryGeoRegionInformation1Code = "GIMI_global_imi"
	INTI_INTERNATIONAL_INSTRUMENT_ProprietaryGeoRegionInformation1Code ProprietaryGeoRegionInformation1Code = "INTI_international_instrument"
	NOTA_NOT_AVAILABLE_ProprietaryGeoRegionInformation1Code ProprietaryGeoRegionInformation1Code = "NOTA_not_available"
	OTHR_OTHER_ProprietaryGeoRegionInformation1Code ProprietaryGeoRegionInformation1Code = "OTHR_other"
	SWFT_SWIFT_ProprietaryGeoRegionInformation1Code ProprietaryGeoRegionInformation1Code = "SWFT_swift"
	TGT2_TARGET2_ProprietaryGeoRegionInformation1Code ProprietaryGeoRegionInformation1Code = "TGT2_target2"
	TCKS_TICKER_SYMBOL_ProprietaryGeoRegionInformation1Code ProprietaryGeoRegionInformation1Code = "TCKS_ticker_symbol"
)
