/*
 * SWIFT Banking Analytics
 *
 * SWIFT Watch Banking Analytics API enables institutions to retrieve their  own SWIFT traffic data and the SWIFT totals, extending to the level of value and currency per market.   **v1.0.11 Release Notes**   * The Test Environment url updated to https://api-pilot.swift.com/bi/banking-analytics/v1  * PaginationLinks Object is defined as optional, as well as property next.   * Response examples were udpated to align with the API contract.   * Example for Market parameter in the request fixed
 *
 * API version: 1.0.11
 * Contact: developer-support@swift.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package analytics

// Specifies the generic status as a result of a method applied to a Resource.
type GenericStatus1 struct {
	Code string `json:"code"`
	Severity *ErrorSeverity3Code `json:"severity"`
	Text string `json:"text"`
	UserMessage string `json:"user_message,omitempty"`
	MoreInfo string `json:"more_info,omitempty"`
}
