/*
 * SWIFT Banking Analytics
 *
 * SWIFT Watch Banking Analytics API enables institutions to retrieve their  own SWIFT traffic data and the SWIFT totals, extending to the level of value and currency per market.   **v1.0.11 Release Notes**   * The Test Environment url updated to https://api-pilot.swift.com/bi/banking-analytics/v1  * PaginationLinks Object is defined as optional, as well as property next.   * Response examples were udpated to align with the API contract.   * Example for Market parameter in the request fixed
 *
 * API version: 1.0.11
 * Contact: developer-support@swift.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package analytics

// Data model describing the banking data resource.
type BankingData1 struct {
	Market *Market1Code `json:"market"`
	ReportingPeriod string `json:"reporting_period"`
	DeliveryStatus *DeliveryStatus1Choice `json:"delivery_status"`
	MessageDefinitionIdentifier *MessageType1Choice `json:"message_definition_identifier"`
	MyInstitution *PartyDetails1 `json:"my_institution"`
	Counterparty *PartyDetails1 `json:"counterparty"`
	GeoRoute *GeoRoute1Choice `json:"geo_route"`
	CustomerRoute *CustomerRoute1Choice `json:"customer_route"`
	TransactionsSent string `json:"transactions_sent,omitempty"`
	TransactionsReceived string `json:"transactions_received,omitempty"`
	TotalSwiftTransactionsSent string `json:"total_swift_transactions_sent,omitempty"`
	TotalSwiftTransactionsReceived string `json:"total_swift_transactions_received,omitempty"`
	Currency *CurrencyDetails1Choice `json:"currency"`
	AmountSent *CurrencyAndAmount5 `json:"amount_sent,omitempty"`
	AmountReceived *CurrencyAndAmount5 `json:"amount_received,omitempty"`
	TotalSwiftAmountSent *CurrencyAndAmount5 `json:"total_swift_amount_sent,omitempty"`
	TotalSwiftAmountReceived *CurrencyAndAmount5 `json:"total_swift_amount_received,omitempty"`
}
