/*
 * SWIFT Banking Analytics
 *
 * SWIFT Watch Banking Analytics API enables institutions to retrieve their  own SWIFT traffic data and the SWIFT totals, extending to the level of value and currency per market.   **v1.0.11 Release Notes**   * The Test Environment url updated to https://api-pilot.swift.com/bi/banking-analytics/v1  * PaginationLinks Object is defined as optional, as well as property next.   * Response examples were udpated to align with the API contract.   * Example for Market parameter in the request fixed
 *
 * API version: 1.0.11
 * Contact: developer-support@swift.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package analytics
// ErrorSeverity3Code : A enum describing the severity of an error
type ErrorSeverity3Code string

// List of ErrorSeverity3Code
const (
	FATAL_ErrorSeverity3Code ErrorSeverity3Code = "Fatal"
	LOGIC_ErrorSeverity3Code ErrorSeverity3Code = "Logic"
	TRANSIENT_ErrorSeverity3Code ErrorSeverity3Code = "Transient"
)
