/*
 * SWIFTRef API
 *
 * SWIFTRef API
 *
 * API version: 1.6.0
 * Contact: developer-support@swift.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swiftref

type SepaPaymentChannel struct {
	// The id of the payment channel (SEPA-compliant CSM)
	Id string `json:"id"`
	// A payment channel has a member_type, the member_type has one of the codes DRCT, IDRC or UKWN
	MemberType string `json:"member_type"`
	// The BIC of the direct participant through which the indirectly reachable BIC can be reached; it may only be present if the payment channel's member is an indirect participant
	DirectParticipant string `json:"direct_participant,omitempty"`
}
