/*
 * SWIFTRef API
 *
 * SWIFTRef API
 *
 * API version: 1.6.0
 * Contact: developer-support@swift.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swiftref

type InlineResponse2006 struct {
	Status *Status `json:"status,omitempty"`
	// The BIC that was validated
	Bic string `json:"bic"`
	// The code VBIC if the BIC is valid
	Validity string `json:"validity"`
	// A date in YYYY-MM-DD format to indicate explicitly on which date the BIC is confirmed to be valid; the timezone is always UTC, hence the \"Z\" suffix will always be present, in compliance with ISO 8601 / RFC 3339
	EffectiveDate string `json:"effective_date"`
}
