/*
 * SWIFTRef API
 *
 * SWIFTRef API
 *
 * API version: 1.6.0
 * Contact: developer-support@swift.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swiftref

type LeiSuccessor struct {
	Lei string `json:"lei,omitempty"`
	Name string `json:"name,omitempty"`
}
