/*
 * SWIFTRef API
 *
 * SWIFTRef API
 *
 * API version: 1.6.0
 * Contact: developer-support@swift.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swiftref

type Address struct {
	// An array of maximum 4 lines (strings) expressing the street address of the BIC, e.g. street name, house number, building name and floor, area
	AddressLines []string `json:"address_lines,omitempty"`
	// Numbered box in a post office, assigned to a person or organisation, where letters are kept until called for
	PostOfficeBox string `json:"post_office_box,omitempty"`
	// Name of a built-up area, with defined boundaries, and a local government
	TownName string `json:"town_name,omitempty"`
	// Identifies a subdivision of a country (for example, state, region, county)
	CountrySubdivision string `json:"country_subdivision,omitempty"`
	// Identifier consisting of a group of letters and/or numbers that is added to a postal address to assist the sorting of mail
	PostCode string `json:"post_code,omitempty"`
	// The country name in English of the institution/branch as indicated in the ISO 3166 list
	CountryName string `json:"country_name"`
	// The ISO 3166-1 alpha-2 code of the country of the institution/branch
	CountryCode string `json:"country_code"`
}
