/*
 * SWIFTRef API
 *
 * SWIFTRef API
 *
 * API version: 1.6.0
 * Contact: developer-support@swift.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swiftref

type SwiftConnectivity struct {
	// True if connected to SWIFT FIN, false otherwise
	Fin bool `json:"fin"`
	// True if used in at least one service on SWIFTNet InterAct, false otherwise
	Interact bool `json:"interact"`
	// True if used in at least one service on SWIFTNet FileAct, false otherwise
	Fileact bool `json:"fileact"`
}
