/*
 * SWIFTRef API
 *
 * SWIFTRef API
 *
 * API version: 1.6.0
 * Contact: developer-support@swift.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swiftref

type InlineResponse20015 struct {
	Status *Status `json:"status,omitempty"`
	// The country code that was validated
	CountryCode string `json:"country_code"`
	// The code VCOC if the country code is valid
	Validity string `json:"validity"`
}
