/*
 * SWIFTRef API
 *
 * SWIFTRef API
 *
 * API version: 1.6.0
 * Contact: developer-support@swift.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swiftref

type ContactDetails struct {
	// Collection of information that identifies a phone number, as defined by telecom services
	PhoneNumber string `json:"phone_number,omitempty"`
	// Collection of information that identifies a FAX number, as defined by telecom services
	FaxNumber string `json:"fax_number,omitempty"`
	// Address for electronic mail (e-mail)
	EmailAddress string `json:"email_address,omitempty"`
	// Address for the Universal Resource Locator (URL), that is used over the www (HTTP) service
	WebAddress string `json:"web_address,omitempty"`
}
