/*
 * SWIFTRef API
 *
 * SWIFTRef API
 *
 * API version: 1.6.0
 * Contact: developer-support@swift.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swiftref

type ShortStatus struct {
	// A repeat of the HTTP status code
	Http string `json:"http"`
	// An error code or status code, unique across all SWIFT APIs
	Code string `json:"code"`
	// Provided in case your application needs to display a short error message to a human end-user
	UserMessage string `json:"user_message,omitempty"`
	// A verbose description for a developer of the possible causes of the error and the possible fixes
	DeveloperMessage string `json:"developer_message,omitempty"`
	// A hyperlink to an explanation of the error for developers, possibly with further pointers to community input
	MoreInfo string `json:"more_info,omitempty"`
}
