/*
 * SWIFTRef API
 *
 * SWIFTRef API
 *
 * API version: 1.6.0
 * Contact: developer-support@swift.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swiftref

type InlineResponse20021 struct {
	Status *Status `json:"status,omitempty"`
	// The account number that was validated
	AccountNumber string `json:"account_number"`
	// The code AVAL if the account number is valid
	Validity string `json:"validity"`
}
