/*
 * SWIFTRef API
 *
 * SWIFTRef API
 *
 * API version: 1.6.0
 * Contact: developer-support@swift.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swiftref

type InlineResponse2002 struct {
	Status *Status `json:"status,omitempty"`
	// The IBAN that was validated
	Iban string `json:"iban"`
	// The ISO 3166-1 alpha-2 code of the country of the institution/branch.
	CountryCode string `json:"country_code"`
	// The checksum extracted from the IBAN
	Checksum string `json:"checksum"`
	// The BANK ID extracted from the IBAN. Its structure (bank ID only or bank ID + branch ID) is as defined by the IBAN BIC LENGTH in the IBANSTRUCTURE file.
	BankId string `json:"bank_id"`
	// Unique and unambiguous identification of a branch of a financial institution.
	BranchId string `json:"branch_id,omitempty"`
	// The remainder of the IBAN including the account number.
	AccountNumber string `json:"account_number"`
	// The length of the IBAN
	Length int32 `json:"length"`
}
