/*
 * SWIFTRef API
 *
 * SWIFTRef API
 *
 * API version: 1.6.0
 * Contact: developer-support@swift.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swiftref

type Lei struct {
	Lei string                            `json:"lei"`
	LegalName string                      `json:"legal_name"`
	Address *Address2                     `json:"address,omitempty"`
	HeadQuartersAddress *Address2         `json:"head_quarters_address,omitempty"`
	LegalJurisdiction string              `json:"legal_jurisdiction,omitempty"`
	LegalForm string                      `json:"legal_form,omitempty"`
	EntityLegalFormCode string            `json:"entity_legal_form_code,omitempty"`
	EntityStatus string                   `json:"entity_status,omitempty"`
	InitialRegistrationDate string        `json:"initial_registration_date,omitempty"`
	LastUpdateDate string                 `json:"last_update_date,omitempty"`
	RegistrationStatus string             `json:"registration_status,omitempty"`
	Associated *LeiAssociated             `json:"associated,omitempty"`
	EntityExpiration *LeiEntityExpiration `json:"entity_expiration,omitempty"`
	Successor *LeiSuccessor               `json:"successor,omitempty"`
}
