/*
 * SWIFTRef API
 *
 * SWIFTRef API
 *
 * API version: 1.6.0
 * Contact: developer-support@swift.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swiftref

type IntermediaryBic struct {
	// Specifies the BIC
	Bic string `json:"bic"`
	// The account for a given BIC
	Account string `json:"account,omitempty"`
}
