/*
 * SWIFTRef API
 *
 * SWIFTRef API
 *
 * API version: 1.6.0
 * Contact: developer-support@swift.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swiftref

type SwiftService struct {
	// Code given by the service provider (SWIFT) to uniquely identify a service it offers
	Code string `json:"code"`
	// Name given by the service provider (SWIFT) to uniquely identify a service it offers
	Name string `json:"name"`
}
