/*
 * SWIFTRef API
 *
 * SWIFTRef API
 *
 * API version: 1.6.0
 * Contact: developer-support@swift.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swiftref

type NationalId struct {
	// The National ID (a synonym for clearing code, routing code, sort code, bank and branch ID) of the institution or branch
	Id string `json:"id"`
	// The type of National ID; if absent, it is the main National ID (MA), otherwise it is Foreign National ID (FN) or Alternative National ID (AN)
	Type_ string `json:"type,omitempty"`
	// The scheme under which the National ID is defined
	Scheme string `json:"scheme"`
}
