/*
 * SWIFTRef API
 *
 * SWIFTRef API
 *
 * API version: 1.6.0
 * Contact: developer-support@swift.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swiftref

type LeiAssociated struct {
	EntityType string `json:"entity_type,omitempty"`
	Lei string `json:"lei,omitempty"`
	EntityName string `json:"entity_name,omitempty"`
}
