/*
 * SWIFTRef API
 *
 * SWIFTRef API
 *
 * API version: 1.6.0
 * Contact: developer-support@swift.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swiftref

type CorrespondentBic struct {
	// Specifies the BIC
	Bic string `json:"bic"`
	// The account for a given BIC
	Account string `json:"account,omitempty"`
	// Indicates if it is a preferred correspondent, true (yes) or false (no)
	Preferred bool `json:"preferred,omitempty"`
}
