/*
 * SWIFTRef API
 *
 * SWIFTRef API
 *
 * API version: 1.6.0
 * Contact: developer-support@swift.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swiftref

type InlineResponse200 struct {
	Status *Status `json:"status,omitempty"`
	// The IBAN that was validated
	Iban string `json:"iban"`
	// The code IVAL if the IBAN is valid
	Validity string `json:"validity"`
}
