/*
 * SWIFTRef API
 *
 * SWIFTRef API
 *
 * API version: 1.6.0
 * Contact: developer-support@swift.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swiftref

type InlineResponse20010 struct {
	Status *Status `json:"status,omitempty"`
	// SEPA CSM through which the BIC is reachable for the supplied SEPA scheme
	PaymentChannels []SepaPaymentChannel `json:"payment_channels"`
	// Adherence BIC11 of the reachable BIC
	AdherenceBic string `json:"adherence_bic,omitempty"`
}
