/*
 * SWIFTRef API
 *
 * SWIFTRef API
 *
 * API version: 1.6.0
 * Contact: developer-support@swift.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swiftref

type CurrencyCountries struct {
	// The ISO country name
	Name string `json:"name"`
	// The ISO 2-letters country code
	Iso2aCode string `json:"iso_2a_code"`
	// The ISO 3-letters country code
	Iso3aCode string `json:"iso_3a_code,omitempty"`
	// The ISO 3-digits country code
	Iso3nCode string `json:"iso_3n_code,omitempty"`
}
