/*
 * Payment Pre-validation API
 *
 * New version of the Bank Account Verification Service (the BAV), BAV v2, for Users and Data Providers. Additionally to BAV v1, depending on the jurisdiction where the account is held and the market practices in use, BAV v2 brings in the validation of the account type and if the creditor name partially matches the account holder name.   **v2.1.1Release Notes**  * Addition of Beneficiary Account Verification   *  Beneficiary Account Verification has been updated to version 2, which includes features to better support domestic systems, future support of ISO20022 addresses and support for systems that may provide answers based on past transactions.  * Schema Organisation8 updated to OrganisationIdentification8
 *
 * API version: 2.1.1
 * Contact: developer-support@swift.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package prevalidation
// CategoryPaymentValidationReason1Code : The list of unique identifiers which describe the reasons for Category Purpose Code validation status. *`UPCP_unrecognized_category_purpose`-The instructed payment category purpose subject to validation could not be found in the payment category purpose data available in the SWIFT repository for the instructed payment context. *`VPCP_valid_category_purpose`-The instructed payment category purpose subject has been successfully validated for the instructed payment context. *`ICTY_invalid_country`-Instructed country code is not a valid country code on the basis of country names obtained from the United Nations (ISO 3166, Alpha-2 code) *`CINP_no_category_purpose_data_available`-No category purpose data available in the SWFIFT repository for the instructed context. This may relate to the country specific requirements not mandating category purpose codes for the instructed context.
type CategoryPaymentValidationReason1Code string

// List of CategoryPaymentValidationReason1Code
const (
	UPCP_UNRECOGNIZED_CATEGORY_PURPOSE_CategoryPaymentValidationReason1Code CategoryPaymentValidationReason1Code = "UPCP_unrecognized_category_purpose"
	VPCP_VALID_CATEGORY_PURPOSE_CategoryPaymentValidationReason1Code CategoryPaymentValidationReason1Code = "VPCP_valid_category_purpose"
	ICTY_INVALID_COUNTRY_CategoryPaymentValidationReason1Code CategoryPaymentValidationReason1Code = "ICTY_invalid_country"
	CINP_NO_CATEGORY_PURPOSE_DATA_AVAILABLE_CategoryPaymentValidationReason1Code CategoryPaymentValidationReason1Code = "CINP_no_category_purpose_data_available"
)
