/*
 * Payment Pre-validation API
 *
 * New version of the Bank Account Verification Service (the BAV), BAV v2, for Users and Data Providers. Additionally to BAV v1, depending on the jurisdiction where the account is held and the market practices in use, BAV v2 brings in the validation of the account type and if the creditor name partially matches the account holder name.   **v2.1.1Release Notes**  * Addition of Beneficiary Account Verification   *  Beneficiary Account Verification has been updated to version 2, which includes features to better support domestic systems, future support of ISO20022 addresses and support for systems that may provide answers based on past transactions.  * Schema Organisation8 updated to OrganisationIdentification8
 *
 * API version: 2.1.1
 * Contact: developer-support@swift.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package prevalidation
// AccountValidationResponse3Code : *`FAIL`-The account identification provided was not successfully validated to an account that can receive funds. *`INCO`-The account identification provided was successfully validated to an account that can receive funds, however, some additional account checks will be performed at transaction time. *`PASS`-The account identification was successfully validated to an account that can receive funds. *`WARN`-The account identification was not successfully validated to an account that can receive funds, however, the responder lacks some information to provide a definite answer.
type AccountValidationResponse3Code string

// List of AccountValidationResponse3Code
const (
	FAIL_AccountValidationResponse3Code AccountValidationResponse3Code = "FAIL"
	INCO_AccountValidationResponse3Code AccountValidationResponse3Code = "INCO"
	PASS_AccountValidationResponse3Code AccountValidationResponse3Code = "PASS"
	WARN_AccountValidationResponse3Code AccountValidationResponse3Code = "WARN"
)
