/*
 * Payment Pre-validation API
 *
 * New version of the Bank Account Verification Service (the BAV), BAV v2, for Users and Data Providers. Additionally to BAV v1, depending on the jurisdiction where the account is held and the market practices in use, BAV v2 brings in the validation of the account type and if the creditor name partially matches the account holder name.   **v2.1.1Release Notes**  * Addition of Beneficiary Account Verification   *  Beneficiary Account Verification has been updated to version 2, which includes features to better support domestic systems, future support of ISO20022 addresses and support for systems that may provide answers based on past transactions.  * Schema Organisation8 updated to OrganisationIdentification8
 *
 * API version: 2.1.1
 * Contact: developer-support@swift.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package prevalidation
// PaymentPurposeValidationCheckCode : The list of unique identifiers for the individual payment purpose validation checks.  *`PCCT_purpose_and_country`-The unique identifier of the individual payment purpose validation check  that validates the instructed payment purpose information against the payment purpose requirements available in the SWIFT repository for the instructed creditor country. *`PCCC_purpose_and_country_and_currency`-The unique identifier of the individual payment purpose validation check  that validates the instructed payment purpose information against the payment purpose requirements available in the SWIFT repository for the instructed creditor country and creditor account currency. *`PCCP_purpose_and_country_and_currency_and_clearing_system`-The unique identifier of the individual payment purpose validation check  that validates the instructed payment purpose information against the payment purpose requirements available in the SWIFT repository for the instructed creditor country, creditor account currency and local clearing system. *`PCCS_purpose_and_country_and_clearing_system`-The unique identifier of the individual payment purpose validation check  that validates the instructed payment purpose information against the payment purpose requirements available in the SWIFT repository for the instructed creditor country and the instructed clearing system.
type PaymentPurposeValidationCheckCode string

// List of PaymentPurposeValidationCheckCode
const (
	PCCT_PURPOSE_AND_COUNTRY_PaymentPurposeValidationCheckCode PaymentPurposeValidationCheckCode = "PCCT_purpose_and_country"
	PCCC_PURPOSE_AND_COUNTRY_AND_CURRENCY_PaymentPurposeValidationCheckCode PaymentPurposeValidationCheckCode = "PCCC_purpose_and_country_and_currency"
	PCCP_PURPOSE_AND_COUNTRY_AND_CURRENCY_AND_CLEARING_SYSTEM_PaymentPurposeValidationCheckCode PaymentPurposeValidationCheckCode = "PCCP_purpose_and_country_and_currency_and_clearing_system"
	PCCS_PURPOSE_AND_COUNTRY_AND_CLEARING_SYSTEM_PaymentPurposeValidationCheckCode PaymentPurposeValidationCheckCode = "PCCS_purpose_and_country_and_clearing_system"
)
