/*
 * Payment Pre-validation API
 *
 * New version of the Bank Account Verification Service (the BAV), BAV v2, for Users and Data Providers. Additionally to BAV v1, depending on the jurisdiction where the account is held and the market practices in use, BAV v2 brings in the validation of the account type and if the creditor name partially matches the account holder name.   **v2.1.1Release Notes**  * Addition of Beneficiary Account Verification   *  Beneficiary Account Verification has been updated to version 2, which includes features to better support domestic systems, future support of ISO20022 addresses and support for systems that may provide answers based on past transactions.  * Schema Organisation8 updated to OrganisationIdentification8
 *
 * API version: 2.1.1
 * Contact: developer-support@swift.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package prevalidation
// PaymentPurposeCodeValidationReason1Code : The list of unique identifiers which describe the reasons for Payment Purpose Code validation status. *`UPPC_unrecognized_purpose_code`-The instructed payment purpose code subject to validation could not be found in the purpose code data available in the SWIFT repository for the instructed payment context. *`VPPC_valid_purpose_code`-The instructed payment purpose code has been successfully validated against the purpose  code list(s) available in the SWIFT repository for the instructed payment context. *`ICTY_invalid_country`-Instructed country code is not a valid country code on the basis of country names obtained from the United Nations (ISO 3166, Alpha-2 code) *`PINP_no_purpose_code_data_available`-No purpose code data available in the SWFIFT repository for the instructed context. This may relate to the country specific requirements not mandating purpose codes for the instructed context.
type PaymentPurposeCodeValidationReason1Code string

// List of PaymentPurposeCodeValidationReason1Code
const (
	UPPC_UNRECOGNIZED_PURPOSE_CODE_PaymentPurposeCodeValidationReason1Code PaymentPurposeCodeValidationReason1Code = "UPPC_unrecognized_purpose_code"
	VPPC_VALID_PURPOSE_CODE_PaymentPurposeCodeValidationReason1Code PaymentPurposeCodeValidationReason1Code = "VPPC_valid_purpose_code"
	ICTY_INVALID_COUNTRY_PaymentPurposeCodeValidationReason1Code PaymentPurposeCodeValidationReason1Code = "ICTY_invalid_country"
	PINP_NO_PURPOSE_CODE_DATA_AVAILABLE_PaymentPurposeCodeValidationReason1Code PaymentPurposeCodeValidationReason1Code = "PINP_no_purpose_code_data_available"
)
