/*
 * Payment Pre-validation API
 *
 * New version of the Bank Account Verification Service (the BAV), BAV v2, for Users and Data Providers. Additionally to BAV v1, depending on the jurisdiction where the account is held and the market practices in use, BAV v2 brings in the validation of the account type and if the creditor name partially matches the account holder name.   **v2.1.1Release Notes**  * Addition of Beneficiary Account Verification   *  Beneficiary Account Verification has been updated to version 2, which includes features to better support domestic systems, future support of ISO20022 addresses and support for systems that may provide answers based on past transactions.  * Schema Organisation8 updated to OrganisationIdentification8
 *
 * API version: 2.1.1
 * Contact: developer-support@swift.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package prevalidation
// AddressType2Code : Specifies the type of address. *`ADDR`-Address is the complete postal address. *`PBOX`-Address is a postal office (PO) box. *`HOME`-Address is the home address. *`BIZZ`-Address is the business address. *`MLTO`-Address is the address to which mail is sent. *`DLVY`-Address is the address to which delivery is to take place.
type AddressType2Code string

// List of AddressType2Code
const (
	ADDR_AddressType2Code AddressType2Code = "ADDR"
	PBOX_AddressType2Code AddressType2Code = "PBOX"
	HOME_AddressType2Code AddressType2Code = "HOME"
	BIZZ_AddressType2Code AddressType2Code = "BIZZ"
	MLTO_AddressType2Code AddressType2Code = "MLTO"
	DLVY_AddressType2Code AddressType2Code = "DLVY"
)
